Committing workflows

diff --git a/.github/workflows/acr_tomcat_README_md.yml b/.github/workflows/acr_tomcat_README_md.yml
--- a/.github/workflows/acr_tomcat_README_md.yml
+++ b/.github/workflows/acr_tomcat_README_md.yml
@@ -1,4 +1,6 @@
 on: 
+  schedule: 
+    - cron: '0 9 * * 2'
   workflow_dispatch: 
 
 name: 'acr/tomcat/README.md'
@@ -12,7 +14,36 @@ jobs:
           creds: '${{ secrets.AZURE_CREDENTIALS }}'
       - uses: 'actions/checkout@v2'
       - run: | 
+          if [[ -z $RESOURCE_GROUP ]]; then
+          export RESOURCE_GROUP=azure-examples-$RANDOM
+          fi
+          export REGION=westus2
+          az group create --name $RESOURCE_GROUP --location $REGION
+          export DELETE_AFTER=$(( `date +%s` + 7200))
+          az group update --name $RESOURCE_GROUP --set tags.'DeleteAfter'="$DELETE_AFTER"
+          if [[ -z $ACR ]]; then
+          export ACR=acr$RANDOM
+          fi
+          az acr create \
+          --name $ACR \
+          --resource-group $RESOURCE_GROUP \
+          --sku Basic \
+          --admin-enabled true
+          
+          cd acr/tomcat
+          
           mvn package
-          export ACR_TOMCAT_IMAGE=acr-tomcat:latest
+          export ACR_TOMCAT_IMAGE=tomcat:latest
           
           az acr build --registry $ACR --image $ACR_TOMCAT_IMAGE .
+          
+          cd ../..
+          
+          
+          export RESULT=$(az acr repository show --name $ACR --image $ACR_TOMCAT_IMAGE)
+          az group delete --name $RESOURCE_GROUP --yes || true
+          
+          if [[ -z $RESULT ]]; then
+          echo "Unable to find $ACR_TOMCAT_IMAGE image"
+          exit 1
+          fi
